name: Deploy Explorer to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Cache Dota 2 Data 💾
        uses: actions/cache@v4
        with:
          path: data
          key: ${{ runner.os }}-dota-data-${{ hashFiles('scripts/fetch-all.ts') }}
          restore-keys: |
            ${{ runner.os }}-dota-data-

      - name: Install dependencies 📦
        run: npm install

      - name: Fetch Dota 2 Data 📡
        run: npm run fetch-all

      - name: Build Static Explorer 🏗️
        run: npm run docs:static-build

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/dist
          branch: gh-pages
